### ISSUE TITLE
Update instructions page (readme.md)

### ISSUE THREAD

**Issue by rocketinventor** [fulldecent/system-bus-radio#33]
The Readme only has instructions for running using ```make``` and seems a little bit outdated.
There is no reference to the JS version _at all_. I would like to propose adding a mention to the JS version.  I would also like to propose suggesting that one can test out the JS version easily with [RawGit](https://rawgit.com/fulldecent/system-bus-radio/master/In%20Javascript/airgap.html). Also, I would add the instruction you wrote on the JS version itself: "If you are opening this file locally (```file://```), Chrome will give you errors. Try using ```php -S localhost:8000``` or similar for a quick web server."

**Comment by fulldecent** [comment]
Thank you, updated

**Comment by rocketinventor** [comment]
@fulldecent Please Fix the link for the JS version.
On rawgit.com:
"Use a _specific tag or commit hash in the URL_ (not a branch). Files are cached permanently based on the URL. Query strings are ignored. I have provided the proper urls in a comment. Please see [my comment on the commit](https://github.com/fulldecent/system-bus-radio/commit/8cce5ef335fbb996a8da00a5a97a1f6d79d41f03#diff-04c6e90faac2675aa89e2176d2eec7d8R13).
