### ISSUE TITLE
running .tune files in terminal

### ISSUE THREAD

**Issue by Robbevdv13** [fulldecent/system-bus-radio#37]
I have downloaded the files and I followed the steps on the GitHub page, but how do I play/run the .tune files in my terminal? 
ps: I am working with a macbook pro 13" 2016﻿

**Comment by fulldecent** [comment]
Thank you, readme is updated in https://github.com/fulldecent/system-bus-radio/commit/735a66f2e3f09426159c43ab6740126c57d8b4e3

---

after you compile, on terminal use like:

```sh
./cmain ../../tunes/mary_had_a_little_lamb.tune
```

depending on which binary and tune you want
