### ISSUE TITLE
Are we missing newlines?

### ISSUE THREAD

**Issue by 7imbrook** [fulldecent/system-bus-radio#4]
Example
```c
printf("Playing / %0.3f seconds / %4.0f Hzn", time, frequency);
```
maybe should be
```c
printf("Playing / %0.3f seconds / %4.0f Hz\n", time, frequency);
```
It just buffering to `stdio` and not printing until the buffers full. Is this a design of the system to avoid overhead of printing and there for get a tighter loop?

**Comment by rocketinventor** [comment]
@7imbrook I think pull request #3 #diff-2045016cb90d1e65d71c2407a2570927L18 fixes this issue. It just needs to be merged.
