### ISSUE TITLE
How can it transmit radio over FM?

### ISSUE THREAD

**Issue by mirimmad** [fulldecent/system-bus-radio#40]

**Comment by ajithmel** [comment]
it can't yet because it just says AM radio.

**Comment by fulldecent** [comment]
Using an FM transmitter!

The fact that AM works is a hack, you can see the documentation that shows how that works. But FM is an entirely different thing.

**Comment by mirimmad** [comment]
Where is the _documentation?_

**Comment by fulldecent** [comment]
It's pretty weak, but it's here in https://github.com/fulldecent/system-bus-radio#technical-explanation

It doesn't mention amplitude modulation by name, but the picture shows why it works as an AM carrier.

The readme could surely be improved in this respect.
