### ISSUE TITLE
MacBook Air with i7 sounds bad?

### ISSUE THREAD

**Issue by MikeRich88** [fulldecent/system-bus-radio#45]
Not really an issue, but I'll hope you'll indulge this misapplication for a quick discussion.

Anyone else have the MacBook Air with the i7?

I hear something, but it sounds pretty bad. I am using a Grundig G3 radio. 

Would the processor make any difference? I tried some different frequencies. 

They all sound bad and I wonder if the i7 actually puts out more noise and garbage and crap. Makes me wonder how the hell this passed FCC at all.

**Comment by fulldecent** [comment]
Aha it must not put out any HARMFUL interference, lol

Yes, the processors all make a difference. Could you please post your test results in https://github.com/fulldecent/system-bus-radio/blob/main/TEST-DATA.tsv as there are other field reports to compare with
