### ISSUE TITLE
kind of a weird request but...

### ISSUE THREAD

**Issue by Andyreptiliana** [fulldecent/system-bus-radio#49]
Hi guys, I got a question for you (please take it seriously, rly, I know it sounds crasy but give me a chance please)
Is there a way this system transmits to 1420mhz ? I know it's a lot but I'm trying to make it work for space purposes like sending messages and stuff right from my computer without the need of anthenas (trying to make a minimmalist instrument over here, just my computer, some mics and I) please let me know if it's possible to at least send signals to devices that are 10 meters or further , I will try to make it work and let you all know if it does.
- Andy.

**Comment by fulldecent** [comment]
Yes, 1420 MHz will work but it is likely you will need to disassemble your computer, i.e. just remove the case. You will very likely not get 10 meters at that frequency. We have not found any frequency that works with that distance yet.

I am working to get to 10 meters but this will likely require specialized antennas and a software defined radio receiver. But I'm working on it.

**Comment by nemanjan00** [comment]
Would PWM fan speed controller maybe be able to transmit stronger signal?

**Comment by fulldecent** [comment]
Yes, other devices are possible. But I do no think you can modulate fast enough to be useful on that controller.

This issue is interesting but it will not result in any software changes, only hopefully people will run it and contribute more useful test data. Closing for now.
