### ISSUE TITLE
Doesn't work on windows, linux or non mac hardware.

### ISSUE THREAD

**Issue by devicemodder** [fulldecent/system-bus-radio#57]
Is there any way to make this work on lets say a thinkpad T60 running linux or even windows 10? Cause i'd love to play around with this, but due to not owning any apple products, i am unable to run it.

**Comment by fulldecent** [comment]
This does compile on both those targets and you should see it work. 

The README has a very tight specification because I can guarantee it works in the setup. But thanks to many people, we have TEST-DATA.csv confirming it works on a variety of platforms.

**Comment by devicemodder** [comment]
Great to know, thanks.
