### ISSUE TITLE
web demo does not work on MacBook Air with m1 chip

### ISSUE THREAD

**Issue by sergiuchuckmisha** [fulldecent/system-bus-radio#63]
[http://fulldecent.github.io/system-bus-radio/](http://fulldecent.github.io/system-bus-radio/)

Was not able to catch something using radio receiver at specified frequency 1560 kHz

**Comment by fulldecent** [comment]
Thank you for checking in. Please also try the compiled versions too as they should be more potent. I have only had success with the web version on Intel processolrs myself
